In [48]:
# Imporações
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# **Analisando os dados**

In [49]:
# Visualiando dados
atletas = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/olimpiadas/120 years of Olympic history/athlete_events.csv')
atletas.head(3)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN

In [50]:
# Visualisando informações do tipo de cada coluna
atletas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  object
 11  City    271116 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB

In [51]:
# Visualisando quantidade de tipo
atletas.dtypes.value_counts()

object     10
float64     3
int64       2
Name: count, dtype: int64

In [52]:
# Visualisando quantidade de valores nulos
atletas.isnull().sum().sort_values(ascending=False).head(5)

Medal     231333
Weight     62875
Height     60171
Age         9474
ID             0
dtype: int64

In [53]:
# Quantidade de linhas e colunas
atletas.shape

(271116, 15)

# **Substituindo os valores nulos**

In [54]:
# Selecionando a coluna medalha e substituindo os valores vazios
atletas.loc[atletas.Medal.isnull(),'Medal'] = 'Sem Medalha'

In [55]:
# Verificando a média dos peso
atletas.Weight.mean()

70.70239290053351

In [56]:
# Verificando a média das altura
atletas.Height.mean()

175.33896987366376

In [57]:
# Verificando a média das idades
atletas.Age.mean()

25.556898357297374

In [58]:
# Selecionando as colunas com altura, peso e idade vazias e substituindo pelas médias
atletas.loc[atletas.Weight.isnull(),'Weight'] = atletas.Weight.mean().round()
atletas.loc[atletas.Height.isnull(),'Height'] = atletas.Height.mean().round()
atletas.loc[atletas.Age.isnull(),'Age'] = atletas.Age.mean().round()

In [59]:
# Conferindo
#atletas.head(10)
atletas.isnull().sum().sort_values(ascending=False).head(5)

ID        0
Name      0
Sex       0
Age       0
Height    0
dtype: int64

# **Informações gerais sobre a quantidade de medalhas dos paises**

In [60]:
# Paises com mais medalhas
atletas.loc[atletas.Medal != 'Sem Medalha'].Team.value_counts().head(10)

Team
United States    5219
Soviet Union     2451
Germany          1984
Great Britain    1673
France           1550
Italy            1527
Sweden           1434
Australia        1306
Canada           1243
Hungary          1127
Name: count, dtype: int64

In [61]:
# Paises com a maior quanidade de ouro
atletas_ouro = atletas.loc[atletas.Medal == 'Gold']
atletas_ouro.Team.value_counts().head(10)

Team
United States    2474
Soviet Union     1058
Germany           679
Italy             535
Great Britain     519
France            455
Sweden            451
Hungary           432
Canada            422
East Germany      369
Name: count, dtype: int64

In [62]:
# Paises com a maior quanidade de prata
atletas_prata = atletas.loc[atletas.Medal == 'Silver']
atletas_prata.Team.value_counts().head(10)

Team
United States    1512
Soviet Union      716
Germany           627
Great Britain     582
France            518
Italy             508
Sweden            476
Australia         453
Canada            413
Russia            351
Name: count, dtype: int64

In [63]:
# Paises com a maior quanidade de bronze
atletas_bronze = atletas.loc[atletas.Medal == 'Bronze']
atletas_bronze.Team.value_counts().head(10)

Team
United States    1233
Germany           678
Soviet Union      677
France            577
Great Britain     572
Australia         511
Sweden            507
Italy             484
Finland           415
Canada            408
Name: count, dtype: int64

In [64]:
# Paises com mais medalhas nos jogos de verão

# Filtrando o DataFrame para incluir apenas as linhas com medalhas e jogos de verão
atletas_verao_com_medalhas = atletas[(atletas.Medal != 'Sem Medalha') & (atletas.Season == 'Summer')]

# Contando as medalhas por país
atletas_verao_com_medalhas.Team.value_counts().head(10)

Team
United States    4686
Soviet Union     2061
Germany          1687
Great Britain    1598
France           1408
Italy            1384
Australia        1290
Hungary          1123
Sweden           1006
Russia            894
Name: count, dtype: int64

In [65]:
# Paises com mais medalha nos jogos de inverno

# Filtrando o DataFrame para incluir apenas as linhas com medalhas e jogos de inverno
atletas_inverno_com_medalhas = atletas[(atletas.Medal != 'Sem Medalha') & (atletas.Season == 'Winter')]

# Contando as medalhas por país
atletas_inverno_com_medalhas.Team.value_counts().head(10)

Team
Canada           575
United States    533
Norway           443
Sweden           428
Finland          426
Soviet Union     390
Germany          297
Austria          244
Russia           216
Switzerland      183
Name: count, dtype: int64

# **Rio 2016**

In [66]:
# Pegando dados dos jogos de 2016
rio_2016 = atletas.loc[atletas.Year == 2016]
rio_2016.head(15)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
80,22,Andreea Aanei,F,22.0,170.0,125.0,Romania,ROU,2016 Summer,2016,Summer,Rio de Janeiro,Weightlifting,Weightlifting Women's Super-Heavyweight,Sem Medalha
139,51,Nstor Abad Sanjun,M,23.0,167.0,64.0,Spain,ESP,2016 Summer,2016,Summer,Rio de Janeiro,Gymnastics,Gymnastics Men's Individual All-Around,Sem Medalha
140,51,Nstor Abad Sanjun,M,23.0,167.0,64.0,Spain,ESP,2016 Summer,2016,Summer,Rio de Janeiro,Gymnastics,Gymnastics Men's Floor Exercise,Sem Medalha
141,51,Nstor Abad Sanjun,M,23.0,167.0,64.0,Spain,ESP,2016 Summer,2016,Summer,Rio de Janeiro,Gymnastics,Gymnastics Men's Parallel Bars,Sem Medalha
142,51,Nstor Abad Sanjun,M,23.0,167.0,64.0,Spain,ESP,2016 Summer,2016,Summer,Rio de Janeiro,Gymnastics,Gymnastics Men's Horizontal Bar,Sem Medalha
143,51,Nstor Abad Sanjun,M,23.0,167.0,64.0,Spain,ESP,2016 Summer,2016,Summer,Rio de Janeiro,Gymnastics,Gymnastics Men's Rings,Sem Medalha
144,51,Nstor Abad Sanjun,M,23.0,167.0,64.0,Spain,ESP,2016 Summer,2016,Summer,Rio de Janeiro,Gymnastics,Gymnastics Men's Pommelled Horse,Sem Medalha
148,55,Antonio Abadia Beci,M,26.0,170.0,65.0,Spain,ESP,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,"Athletics Men's 5,000 metres",Sem Medalha
158,62,Giovanni Abagnale,M,21.0,198.0,90.0,Italy,ITA,2016 Summer,2016,Summer,Rio de Janeiro,Rowing,Rowing Men's Coxless Pairs,Bronze
161,65,Patimat Abakarova,F,21.0,165.0,49.0,Azerbaijan,AZE,2016 Summer,2016,Summer,Rio de Janeiro,Taekwondo,Taekwondo Women's Flyweight,Bronze
175,73,Luc Abalo,M,31.0,182.0,86.0,France,FRA,2016 Summer,2016,Summer,Rio de Janeiro,Handball,Handball Men's Handball,Silver
217,105,Ilyas Abbadi,M,23.0,175.0,75.0,Algeria,ALG,2016 Summer,2016,Summer,Rio de Janeiro,Boxing,Boxing Men's Middleweight,Sem Medalha
232,110,Abubakar Abbas Abbas,M,20.0,175.0,66.0,Bahrain,BRN,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,Athletics Men's 400 metres,Sem Medalha
263,135,Lois Abbingh,F,23.0,178.0,72.0,Netherlands,NED,2016 Summer,2016,Summer,Rio de Janeiro,Handball,Handball Women's Handball,Sem Medalha
267,138,Salwan Jasim Abbood Abbood,M,24.0,180.0,104.0,Iraq,IRQ,2016 Summer,2016,Summer,Rio de Janeiro,Weightlifting,Weightlifting Men's Heavyweight,Sem Medalha

In [67]:
rio_2016.shape

(13688, 15)

In [68]:
# Paises com mais medalhas
rio_2016.loc[rio_2016.Medal != 'Sem Medalha'].Team.value_counts().head(12)

Team
United States    256
Germany          157
Great Britain    145
Russia           113
China            109
France            96
Australia         82
Italy             70
Canada            69
Japan             64
Serbia            54
Brazil            46
Name: count, dtype: int64